server:
  port: 8761

# eureka server does not need to be registered or fetched
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
#    enable-self-preservation: false